Convert the path LSP setting to a list if it is a string  (#402)
## Summary

I ran into a subtle issue today where I provided a single string path:
```lua
 require('lspconfig').ruff_lsp.setup {
   init_options = {
     settings = {
     path = '~/.pyenv/shims/ruff',
```

Which would result in the following error: 

```
PermissionError: [Errno 13] Permission denied: '/'
``` 

This is because we loop over the path in variable, but of course in
Python, you can loop over a string and get `/` as the first result

```python
for path in settings["path"]:
```

This change will convert the str to a simple list in case the user
provides a single path rather than a list.

## Test Plan

tested locally